apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: appsetcoins
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - clusters: {}
        - list:
            elements:
            - component: hasher
              chart: generic
            - component: redis
              chart: generic
            - component: rng
              chart: generic
            - component: webui
              chart: generic
            - component: worker
              chart: generic
  template:
    metadata:
      name: "{{.nameNormalized}}-{{.component}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: "https://github.com/jpetazzo/2026-09-m3.git"
        targetRevision: main
        path: charts/{{.chart}}
        helm:
          releaseName: "{{.component}}"
          valueFiles:
          - /apps/argocoins/values-{{.component}}.yaml
          - /apps/argocoins/values-{{.component}}-{{.nameNormalized}}.yaml
      destination:
        server: "{{.server}}"
        namespace: "appsetcoins"
      syncPolicy:
        automated:
          enabled: true
        syncOptions:
        - CreateNamespace=true
