apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hydrate: normal
  name: dockercoins-redis
  namespace: argocd
spec:
  destination:
    namespace: argodemo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: redis
      valueFiles:
      - /apps/argocoins/values-redis.yaml
    path: charts/generic
    repoURL: https://github.com/jpetazzo/2026-09-m3.git
