---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: purple
  name: purple
  namespace: fluxdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purple
  template:
    metadata:
      labels:
        app: purple
    spec:
      containers:
      - image: jpetazzo/color
        name: color
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: purple
    owner: jp
  name: purple
  namespace: fluxdemo
spec:
  ports:
  - port: 80
  selector:
    app: purple
