apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/apps
    repoURL: https://github.com/jpetazzo/2026-09-m3.git
  syncPolicy:
    automated:
      enabled: true

